### ISSUE TITLE
RAML 1.0 support

### ISSUE THREAD

**Issue by yamsellem** [wdullaer/raml2slate#1]
Hi,

Love what you're doing here!

Any plan to support RAML 1.0?
It will be a great help.

Thanks.

_ps. I guess this is related to the lack of support of raml2md of RAML 1.0, [more about this](https://github.com/raml2html/raml2html/issues/254#issuecomment-254044025)_

**Comment by wdullaer** [comment]
You guessed right.
Once those add 1.0 support, this should get that as well (it doesn't support many fancy features right now)

**Comment by sichvoge** [comment]
Why not using [raml2obj](https://github.com/raml2html/raml2obj)? Its used in raml2html and raml2md.

**Comment by wdullaer** [comment]
A combination of history and lack of time :-)

**Comment by sichvoge** [comment]
Are you purely using the output from raml2md?

**Comment by sichvoge** [comment]
Very nice @wdullaer! Thanks for making that true 👍
